name: Destroy AWS Infra

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "Enter AWS Region"
        required: true
      bucket_name:
        description: "Enter S3 bucket name used earlier"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ github.event.inputs.bucket_name }}" \
            -backend-config="key=terraform/state/infra.tfstate" \
            -backend-config="region=${{ github.event.inputs.aws_region }}" \
            -backend-config="dynamodb_table=tf-lock-${{ github.event.inputs.bucket_name }}" \
            -backend-config="encrypt=true"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Delete all objects inside the bucket
        run: |
          aws s3 rm s3://${{ github.event.inputs.bucket_name }} --recursive || true

      - name: Delete S3 bucket
        run: |
          aws s3api delete-bucket \
            --bucket ${{ github.event.inputs.bucket_name }} \
            --region ${{ github.event.inputs.aws_region }} || true

      - name: Delete DynamoDB table
        run: |
          aws dynamodb delete-table \
            --table-name tf-lock-${{ github.event.inputs.bucket_name }} || true
