name: Destroy AWS Infra

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
        default: 'us-east-1'
      bucket_name:
        description: "S3 bucket name for backend"
        required: true
      vpc_name:
        description: "VPC Name"
        required: true
      subnet_name:
        description: "Subnet Name"
        required: true
      instance_name:
        description: "EC2 Instance Name"
        required: true
      key_name:
        description: "Key pair name (optional)"
        required: false
        default: ''

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ github.event.inputs.bucket_name }}" \
            -backend-config="key=terraform/state/infra.tfstate" \
            -backend-config="region=${{ github.event.inputs.aws_region }}" \
            -backend-config="dynamodb_table=tf-lock-${{ github.event.inputs.bucket_name }}" \
            -backend-config="encrypt=true"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var="aws_region=${{ github.event.inputs.aws_region }}" \
            -var="vpc_name=${{ github.event.inputs.vpc_name }}" \
            -var="subnet_name=${{ github.event.inputs.subnet_name }}" \
            -var="instance_name=${{ github.event.inputs.instance_name }}" \
            -var="key_name=${{ github.event.inputs.key_name }}"
